/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.forms;

import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JRadioButton;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Dunja
 */
public class FrmWallet extends javax.swing.JFrame {

    /**
     * Creates new form FrmWallet
     */
    public FrmWallet() {
        initComponents();
        GroupButton();
        formatField();
    }


    public JRadioButton getRbDescending() {
        return rbDateSort;
    }

    public JFormattedTextField getjFormattedTextFieldDate() {
        return jFormattedTextFieldDate;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void GroupButton(){
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbIncome);
        bg.add(rbOutflow);
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(rbDateSort);
        bg2.add(rbAmountSort);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTranscactions = new javax.swing.JTable();
        lblCurrentBalance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAddTransaction = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox();
        rbIncome = new javax.swing.JRadioButton();
        rbOutflow = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnSaveChanges = new javax.swing.JButton();
        btnDeleteTransaction = new javax.swing.JButton();
        CmbCategoryFilter = new javax.swing.JComboBox();
        cbFilter = new javax.swing.JCheckBox();
        lblAmountError = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnCreateCategory = new javax.swing.JButton();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        rbDateSort = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbAmountSort = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTranscactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTranscactions);

        lblCurrentBalance.setText("Current balance:");

        jLabel1.setText("Transaction history:");

        btnAddTransaction.setText("Add transaction");

        jLabel2.setText("Category:");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rbIncome.setText("Income");

        rbOutflow.setText("Outflow");

        jLabel3.setText("Amount:");

        btnSaveChanges.setText("Save changes");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnDeleteTransaction.setText("Delete selected transaction");
        btnDeleteTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTransactionActionPerformed(evt);
            }
        });

        CmbCategoryFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFilter.setText("Filter transactions by category:");

        lblClock.setText("CLOCK");

        btnCancel.setText("Cancel");

        btnCreateCategory.setText("Create new category");
        btnCreateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCategoryActionPerformed(evt);
            }
        });

        jLabel4.setText("Date:");

        rbDateSort.setText("Sort by date (newest first)");

        jLabel5.setText("Sort transactions by date:");

        rbAmountSort.setText("Sort by amount (descending)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddTransaction)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbIncome)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbOutflow))
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAmountError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(lblCurrentBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblClock)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFilter)
                            .addComponent(rbDateSort)
                            .addComponent(jLabel5)
                            .addComponent(rbAmountSort)))
                    .addComponent(CmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClock)
                            .addComponent(btnCreateCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbIncome)
                            .addComponent(rbOutflow))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmountError)
                            .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddTransaction)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnDeleteTransaction))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(cbFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDateSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAmountSort)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(lblCurrentBalance)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveChanges)
                    .addComponent(btnCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnCreateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateCategoryActionPerformed

    private void btnDeleteTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTransactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteTransactionActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmWallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbCategoryFilter;
    private javax.swing.JButton btnAddTransaction;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateCategory;
    private javax.swing.JButton btnDeleteTransaction;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JCheckBox cbFilter;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmountError;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JRadioButton rbAmountSort;
    private javax.swing.JRadioButton rbDateSort;
    private javax.swing.JRadioButton rbIncome;
    private javax.swing.JRadioButton rbOutflow;
    private javax.swing.JTable tblTranscactions;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnAddTransaction() {
        return btnAddTransaction;
    }

    public javax.swing.JButton getBtnDeleteTransaction() {
        return btnDeleteTransaction;
    }

    public javax.swing.JButton getBtnSaveChanges() {
        return btnSaveChanges;
    }

    public javax.swing.JComboBox getCmbCategory() {
        return cmbCategory;
    }

    public javax.swing.JLabel getLblCurrentBalance() {
        return lblCurrentBalance;
    }

    public javax.swing.JRadioButton getRbIncome() {
        return rbIncome;
    }

    public javax.swing.JRadioButton getRbOutflow() {
        return rbOutflow;
    }

    public javax.swing.JTable getTblTranscactions() {
        return tblTranscactions;
    }

    public javax.swing.JTextField getTxtAmount() {
        return txtAmount;
    }

    public javax.swing.JComboBox getCmbCategoryFilter() {
        return CmbCategoryFilter;
    }

    public javax.swing.JCheckBox getCbFilter() {
        return cbFilter;
    }

    public void addTransactionAddActionListener(ActionListener actionListener) {
        btnAddTransaction.addActionListener(actionListener);
    }

    public void deleteTransactionAddActionListener(ActionListener actionListener) {
        btnDeleteTransaction.addActionListener(actionListener);
    }

    public void saveChangesAddActionListener(ActionListener actionListener) {
        btnSaveChanges.addActionListener(actionListener);
    }

    public javax.swing.JLabel getLblAmountError() {
        return lblAmountError;
    }

    public javax.swing.JLabel getLblClock() {
        return lblClock;
    }

    public void cancelAddActionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }

    public void createCategoryAddActionListener(ActionListener actionListener) {
        btnCreateCategory.addActionListener(actionListener);
    }

    public void cbFilterAddActionListener(ActionListener actionListener) {
        cbFilter.addActionListener(actionListener);
    }

    public void rbSortAmountAddActionListener(ActionListener actionListener) {
        rbAmountSort.addActionListener(actionListener);
    }

    public void rbSortDateDescendingAddActionListener(ActionListener actionListener) {
        rbDateSort.addActionListener(actionListener);
    }

    public JRadioButton getRbAmountSort() {
        return rbAmountSort;
    }

    public JRadioButton getRbDateSort() {
        return rbDateSort;
    }
    

    private void formatField() {
        try {
            MaskFormatter mask = new MaskFormatter("##/##/#### ##:##");
            jFormattedTextFieldDate.setFormatterFactory(new DefaultFormatterFactory(mask));
        } catch (ParseException ex) {
            Logger.getLogger(FrmWallet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
}
